# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

  # I was thinking that maybe I could populate a test DB for development only?!?
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *TEST